var iTechArt = iTechArt || {};
iTechArt.training = iTechArt.training || {};
iTechArt.training.utils = iTechArt.training.utils || {};

/**
 *  Implement linear unfold function that returns a sequence that contains the elements generated by the given computation:
 *
 *      F (callback, initialValue)
 *
 *  callback: A function that takes the current state and returns a tuple consisting of
 *            the next element of the sequence and the next state value. Callback accepts
 *            current value and produces new state and element. Unfold stops upon falsy
 *            value returned by the callback.
 *
 *  initialValue: the initial state value
 */


iTechArt.training.utils.linearUnfold = function(callback, initialValue){
    var resultCollection = [];

    function processIteration(tuple){
        if (tuple){
            resultCollection.push(tuple.value);
            processIteration(callback.call(undefined, tuple.state));
        }
    }

    processIteration(callback.call(undefined, initialValue));

    return resultCollection;
};